apiVersion: apps/v1
kind: Deployment
metadata:
  name: still-deployment
  labels:
    app: still
spec:
  replicas: 1
  selector:
    matchLabels:
      app: still
  template:
    metadata:
      labels:
        app: still
    spec:
      containers:
        - name: still
          image: "hdghg/still:latest"
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-0.kafka-headless.default.svc.cluster.local:9092
